# Generated by Django 6.0.4 on 2026-04-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimensaoJusticaClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Dimensão de justiça climática',
                'verbose_name_plural': 'Dimensões de justiça climática',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'EFS',
                'verbose_name_plural': 'EFS',
                'ordering': ['pais__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoVulneravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo vulnerável',
                'verbose_name_plural': 'Grupos vulneráveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'PaÃ\xads',
                'verbose_name_plural': 'PaÃ\xadses',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de experiência',
                'verbose_name_plural': 'Tipos de experiência',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('ano_execucao', models.PositiveIntegerField()),
                ('status_iniciativa', models.CharField(choices=[('planejamento', 'Planejamento'), ('execucao', 'Execução'), ('concluida', 'ConcluÃ\xadda')], default='planejamento', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('problema_climatico', models.TextField(blank=True)),
                ('relacao_adaptacao_mitigacao_gestao_desastres', models.TextField(blank=True)),
                ('riscos_climaticos', models.TextField(blank=True)),
                ('enfoque_justica_climatica', models.TextField(blank=True)),
                ('impactos_diferenciados', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('perguntas_chave', models.TextField(blank=True)),
                ('criterios_utilizados', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True)),
                ('fontes_informacao', models.TextField(blank=True)),
                ('resultados', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('mudancas_ou_impactos', models.TextField(blank=True)),
                ('motivo_boa_pratica', models.TextField(blank=True)),
                ('elementos_replicaveis', models.TextField(blank=True)),
                ('dificuldades', models.TextField(blank=True)),
                ('licoes_aprendidas', models.TextField(blank=True)),
                ('o_que_fariam_diferente', models.TextField(blank=True)),
                ('replicabilidade', models.TextField(blank=True)),
                ('necessidades_para_replicacao', models.TextField(blank=True)),
                ('ferramentas_metodologias_uteis', models.TextField(blank=True)),
                ('temas_sugeridos_para_guia', models.TextField(blank=True)),
                ('apoio_requerido_pelas_efs', models.TextField(blank=True)),
                ('status_publicacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dimensoes_consideradas', models.ManyToManyField(blank=True, related_name='experiencias', to='praticas.dimensaojusticaclimatica')),
                ('efs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiencias', to='praticas.efs')),
                ('grupos_vulneraveis', models.ManyToManyField(blank=True, related_name='experiencias', to='praticas.grupovulneravel')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiencias', to='praticas.pais')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiencias', to='praticas.setor')),
                ('tipo_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiencias', to='praticas.tipoexperiencia')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-ano_execucao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='anexos_experiencias/')),
                ('url_externa', models.URLField(blank=True)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='praticas.experiencia')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['experiencia', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='efs',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efs', to='praticas.pais'),
        ),
        migrations.CreateModel(
            name='BancoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_recurso', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('dimensoes', models.ManyToManyField(blank=True, related_name='recursos_banco_tecnico', to='praticas.dimensaojusticaclimatica')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_banco_tecnico', to='praticas.setor')),
            ],
            options={
                'verbose_name': 'Banco técnico',
                'verbose_name_plural': 'Banco técnico',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='efs',
            unique_together={('nome', 'pais')},
        ),
    ]
