# Generated by Django 6.0.4 on 2026-04-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0006_alter_experiencia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaEdicaoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contato', models.EmailField(max_length=254)),
                ('comentario_autor', models.TextField(blank=True)),
                ('comentario_revisor', models.TextField(blank=True)),
                ('dados_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_revisao', 'Em revisao'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_edicao', to='praticas.experiencia')),
            ],
            options={
                'verbose_name': 'Proposta de edicao',
                'verbose_name_plural': 'Propostas de edicao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
