# Generated by Django 6.0.7 on 2026-08-01 16:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0009_autor_experiencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fonte', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Informe um hash SHA-256 hexadecimal com 64 caracteres.', regex='^[0-9a-fA-F]{64}$')])),
                ('versao_fonte', models.CharField(max_length=100)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em execucao'), ('concluido', 'Concluido'), ('com_divergencias', 'Com divergencias'), ('falhou', 'Falhou'), ('revertido', 'Revertido'), ('reversao_parcial', 'Reversao parcial')], default='pendente', max_length=30)),
                ('contagens_esperadas', models.JSONField(default=dict)),
                ('contagens_realizadas', models.JSONField(default=dict)),
                ('relatorio_divergencias', models.JSONField(default=dict)),
                ('mensagem_sanitizada', models.TextField(blank=True)),
                ('revertido_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_reversao', models.TextField(blank=True)),
                ('executado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacao_executados', to=settings.AUTH_USER_MODEL)),
                ('revertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacao_revertidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importacao de conteudo',
                'verbose_name_plural': 'Lotes de importacao de conteudo',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemLoteImportacaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(choices=[('marco', 'Marco'), ('ferramenta', 'Ferramenta'), ('versao_guia', 'Versao do guia'), ('eixo', 'Eixo'), ('subeixo', 'Subeixo'), ('subarea', 'Subarea'), ('pergunta', 'Pergunta'), ('referencia', 'Referencia'), ('experiencia_pergunta_guia', 'Experiencia e pergunta do guia'), ('vinculo_usuario_efs', 'Vinculo usuario-EFS'), ('episodio_vinculo_usuario_efs', 'Episodio de vinculo usuario-EFS'), ('atribuicao_papel_vinculo', 'Atribuicao de papel no vinculo')], max_length=50)),
                ('codigo_origem', models.CharField(max_length=160)),
                ('objeto_pk', models.CharField(blank=True, max_length=64)),
                ('operacao', models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado'), ('ignorado', 'Ignorado'), ('falhou', 'Falhou')], max_length=20)),
                ('snapshot_anterior', models.JSONField(default=dict)),
                ('status_rollback', models.CharField(choices=[('nao_aplicavel', 'Nao aplicavel'), ('pendente', 'Pendente'), ('revertido', 'Revertido'), ('bloqueado', 'Bloqueado')], default='nao_aplicavel', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='praticas.loteimportacaoconteudo')),
            ],
            options={
                'verbose_name': 'Item de lote de importacao de conteudo',
                'verbose_name_plural': 'Itens de lote de importacao de conteudo',
                'ordering': ['lote', 'entidade', 'codigo_origem'],
            },
        ),
        migrations.AddIndex(
            model_name='loteimportacaoconteudo',
            index=models.Index(fields=['status', '-iniciado_em'], name='praticas_lo_status_9b876d_idx'),
        ),
        migrations.AddIndex(
            model_name='loteimportacaoconteudo',
            index=models.Index(fields=['sha256', 'versao_fonte'], name='praticas_lo_sha256_f451d4_idx'),
        ),
        migrations.AddIndex(
            model_name='loteimportacaoconteudo',
            index=models.Index(fields=['executado_por', '-iniciado_em'], name='praticas_lo_executa_fc465a_idx'),
        ),
        migrations.AddConstraint(
            model_name='loteimportacaoconteudo',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-fA-F]{64}$')), name='lote_sha256_hex_64'),
        ),
        migrations.AddConstraint(
            model_name='loteimportacaoconteudo',
            constraint=models.CheckConstraint(condition=models.Q(('finalizado_em__isnull', True), ('finalizado_em__gte', models.F('iniciado_em')), _connector='OR'), name='lote_final_ge_inicio'),
        ),
        migrations.AddConstraint(
            model_name='loteimportacaoconteudo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('concluido', 'com_divergencias', 'falhou', 'revertido', 'reversao_parcial')), _negated=True), ('finalizado_em__isnull', False), _connector='OR'), name='lote_status_final_com_data'),
        ),
        migrations.AddConstraint(
            model_name='loteimportacaoconteudo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'falhou'), _negated=True), models.Q(models.Q(('mensagem_sanitizada', ''), _negated=True), models.Q(('contagens_realizadas', {}), _negated=True)), _connector='OR'), name='lote_falha_detalhada'),
        ),
        migrations.AddConstraint(
            model_name='loteimportacaoconteudo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('revertido', 'reversao_parcial')), _negated=True), models.Q(('revertido_em__isnull', False), ('revertido_por__isnull', False), models.Q(('justificativa_reversao', ''), _negated=True)), _connector='OR'), name='lote_reversao_detalhada'),
        ),
        migrations.AddIndex(
            model_name='itemloteimportacaoconteudo',
            index=models.Index(fields=['lote', 'operacao'], name='praticas_it_lote_id_dfe637_idx'),
        ),
        migrations.AddIndex(
            model_name='itemloteimportacaoconteudo',
            index=models.Index(fields=['entidade', 'objeto_pk'], name='praticas_it_entidad_bb84c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemloteimportacaoconteudo',
            constraint=models.UniqueConstraint(fields=('lote', 'entidade', 'codigo_origem'), name='item_lote_origem_unico'),
        ),
    ]
