# Generated by Django 6.0.7 on 2026-08-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0010_fase2a1_lote_importacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodioVinculoUsuarioEFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('rejeitado', 'Rejeitado')], max_length=20)),
                ('origem', models.CharField(choices=[('solicitacao', 'Solicitacao'), ('administracao', 'Administracao'), ('migracao', 'Migracao')], max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_decisao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episodios_vinculo_decididos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Episodio de vinculo usuario-EFS',
                'verbose_name_plural': 'Episodios de vinculo usuario-EFS',
                'ordering': ['-solicitado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PapelInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_es', models.CharField(max_length=100)),
                ('nome_en', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('descricao_es', models.TextField(blank=True)),
                ('descricao_en', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Papel institucional',
                'verbose_name_plural': 'Papeis institucionais',
                'ordering': ['ordem', 'codigo'],
                'indexes': [models.Index(fields=['ativo', 'ordem'], name='praticas_pa_ativo_883631_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoPapelVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_revogacao', models.TextField(blank=True)),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papeis_institucionais_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('revogado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papeis_institucionais_revogados', to=settings.AUTH_USER_MODEL)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='praticas.episodiovinculousuarioefs')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='praticas.papelinstitucional')),
            ],
            options={
                'verbose_name': 'Atribuicao de papel no vinculo',
                'verbose_name_plural': 'Atribuicoes de papel no vinculo',
                'ordering': ['episodio', 'papel', '-atribuido_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuarioEFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('efs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_usuarios', to='praticas.efs')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_efs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo usuario-EFS',
                'verbose_name_plural': 'Vinculos usuario-EFS',
                'ordering': ['efs__nome', 'usuario__username'],
            },
        ),
        migrations.AddField(
            model_name='episodiovinculousuarioefs',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodios', to='praticas.vinculousuarioefs'),
        ),
        migrations.CreateModel(
            name='EventoVinculoUsuarioEFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('solicitado', 'Solicitado'), ('ativado', 'Ativado'), ('rejeitado', 'Rejeitado'), ('suspenso', 'Suspenso'), ('reativado', 'Reativado'), ('encerrado', 'Encerrado'), ('papel_adicionado', 'Papel adicionado'), ('papel_revogado', 'Papel revogado')], max_length=30)),
                ('status_anterior', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('rejeitado', 'Rejeitado')], max_length=20)),
                ('status_novo', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('rejeitado', 'Rejeitado')], max_length=20)),
                ('justificativa', models.TextField(blank=True)),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('atribuicao_papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='praticas.atribuicaopapelvinculo')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='praticas.episodiovinculousuarioefs')),
                ('item_lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_vinculo', to='praticas.itemloteimportacaoconteudo')),
                ('lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_vinculo', to='praticas.loteimportacaoconteudo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_vinculo_efs', to=settings.AUTH_USER_MODEL)),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_vinculo', to='praticas.papelinstitucional')),
            ],
            options={
                'verbose_name': 'Evento de vinculo usuario-EFS',
                'verbose_name_plural': 'Eventos de vinculo usuario-EFS',
                'ordering': ['-ocorrido_em', '-pk'],
                'indexes': [models.Index(fields=['episodio', '-ocorrido_em'], name='praticas_ev_episodi_310bad_idx'), models.Index(fields=['papel', '-ocorrido_em'], name='praticas_ev_papel_i_5a8020_idx'), models.Index(fields=['responsavel', '-ocorrido_em'], name='praticas_ev_respons_78ca4c_idx'), models.Index(fields=['lote_origem', 'ocorrido_em'], name='praticas_ev_lote_or_6775f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('acao__in', ('papel_adicionado', 'papel_revogado')), _negated=True), ('papel__isnull', False), _connector='OR'), name='evento_papel_exige_papel'), models.CheckConstraint(condition=models.Q(('item_lote_origem__isnull', True), ('lote_origem__isnull', False), _connector='OR'), name='evento_item_exige_lote')],
            },
        ),
        migrations.AddIndex(
            model_name='atribuicaopapelvinculo',
            index=models.Index(fields=['episodio', 'revogado_em'], name='praticas_at_episodi_f2dfa8_idx'),
        ),
        migrations.AddIndex(
            model_name='atribuicaopapelvinculo',
            index=models.Index(fields=['papel', 'revogado_em'], name='praticas_at_papel_i_07c11a_idx'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaopapelvinculo',
            constraint=models.UniqueConstraint(condition=models.Q(('revogado_em__isnull', True)), fields=('episodio', 'papel'), name='atribuicao_ativa_unica'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaopapelvinculo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revogado_em__isnull', True), ('revogado_por__isnull', True), ('justificativa_revogacao', '')), models.Q(('revogado_em__isnull', False), ('revogado_por__isnull', False), models.Q(('justificativa_revogacao', ''), _negated=True)), _connector='OR'), name='atribuicao_revogacao_completa'),
        ),
        migrations.AddConstraint(
            model_name='vinculousuarioefs',
            constraint=models.UniqueConstraint(fields=('usuario', 'efs'), name='vinculo_usuario_efs_unico'),
        ),
        migrations.AddIndex(
            model_name='episodiovinculousuarioefs',
            index=models.Index(fields=['vinculo', 'status'], name='praticas_ep_vinculo_e068cc_idx'),
        ),
        migrations.AddIndex(
            model_name='episodiovinculousuarioefs',
            index=models.Index(fields=['status', 'data_fim'], name='praticas_ep_status_b7e17b_idx'),
        ),
        migrations.AddIndex(
            model_name='episodiovinculousuarioefs',
            index=models.Index(fields=['decidido_por', '-decidido_em'], name='praticas_ep_decidid_02024a_idx'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pendente', 'ativo', 'suspenso'))), fields=('vinculo',), name='episodio_corrente_unico'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), models.Q(('data_inicio__isnull', False), ('data_fim__gte', models.F('data_inicio'))), _connector='OR'), name='episodio_fim_ge_inicio'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ativo'), _negated=True), models.Q(('data_inicio__isnull', False), ('decidido_em__isnull', False), ('decidido_por__isnull', False)), _connector='OR'), name='episodio_ativo_decidido'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'suspenso'), _negated=True), ('data_inicio__isnull', False), _connector='OR'), name='episodio_suspenso_com_inicio'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('rejeitado', 'suspenso', 'encerrado')), _negated=True), models.Q(('decidido_em__isnull', False), ('decidido_por__isnull', False), models.Q(('justificativa_decisao', ''), _negated=True)), _connector='OR'), name='episodio_decisao_detalhada'),
        ),
        migrations.AddConstraint(
            model_name='episodiovinculousuarioefs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'encerrado'), _negated=True), ('data_fim__isnull', False), _connector='OR'), name='episodio_encerrado_com_fim'),
        ),
    ]
