# Generated by Django 6.0.7 on 2026-08-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0011_fase2a1_vinculo_efs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloteimportacaoconteudo',
            name='entidade',
            field=models.CharField(choices=[('marco', 'Marco'), ('ferramenta', 'Ferramenta'), ('setor', 'Setor'), ('versao_guia', 'Versao do guia'), ('eixo', 'Eixo'), ('subeixo', 'Subeixo'), ('subarea', 'Subarea'), ('pergunta', 'Pergunta'), ('referencia', 'Referencia'), ('experiencia_pergunta_guia', 'Experiencia e pergunta do guia'), ('vinculo_usuario_efs', 'Vinculo usuario-EFS'), ('episodio_vinculo_usuario_efs', 'Episodio de vinculo usuario-EFS'), ('atribuicao_papel_vinculo', 'Atribuicao de papel no vinculo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemloteimportacaoconteudo',
            name='snapshot_anterior',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=160, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=220)),
                ('titulo_es', models.CharField(max_length=220)),
                ('titulo_en', models.CharField(blank=True, max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('descricao_es', models.TextField()),
                ('descricao_en', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=500)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_importadas', to='praticas.loteimportacaoconteudo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='praticas.setor')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['ordem', 'titulo_es'],
                'indexes': [models.Index(fields=['situacao', 'ordem'], name='ferramenta_status_ordem'), models.Index(fields=['setor', 'situacao'], name='ferramenta_setor_status')],
                'constraints': [models.UniqueConstraint(fields=('ordem',), name='ferramenta_ordem_unica')],
            },
        ),
    ]
