# Generated by Django 6.0.7 on 2026-08-05 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0012_fase2c_ferramenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EixoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('nome_es', models.CharField(max_length=220)),
                ('ordem', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Eixo do guia',
                'verbose_name_plural': 'Eixos do guia',
                'ordering': ['versao', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SetorGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('nome_es', models.CharField(max_length=220)),
                ('ordem', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Setor do guia',
                'verbose_name_plural': 'Setores do guia',
                'ordering': ['versao', 'ordem', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='itemloteimportacaoconteudo',
            name='entidade',
            field=models.CharField(choices=[('marco', 'Marco'), ('ferramenta', 'Ferramenta'), ('setor', 'Setor'), ('setor_guia', 'Setor do guia'), ('versao_guia', 'Versao do guia'), ('eixo', 'Eixo'), ('subeixo', 'Subeixo'), ('subarea', 'Subarea'), ('pergunta', 'Pergunta'), ('referencia', 'Referencia'), ('subarea_referencia_guia', 'Ocorrencia de referencia em subarea'), ('experiencia_pergunta_guia', 'Experiencia e pergunta do guia'), ('vinculo_usuario_efs', 'Vinculo usuario-EFS'), ('episodio_vinculo_usuario_efs', 'Episodio de vinculo usuario-EFS'), ('atribuicao_papel_vinculo', 'Atribuicao de papel no vinculo')], max_length=50),
        ),
        migrations.CreateModel(
            name='VersaoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=100, unique=True)),
                ('fonte', models.CharField(max_length=500)),
                ('sha256_fonte', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Informe um hash SHA-256 hexadecimal com 64 caracteres.', regex='^[0-9a-fA-F]{64}$')])),
                ('idioma_canonico', models.CharField(default='es', editable=False, max_length=5)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada')], default='rascunho', max_length=20)),
                ('vigente', models.BooleanField(default=False)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_guia', to='praticas.loteimportacaoconteudo')),
            ],
            options={
                'verbose_name': 'Versao do guia',
                'verbose_name_plural': 'Versoes do guia',
                'ordering': ['-vigente', '-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubeixoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('nome_es', models.CharField(max_length=220)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subeixos', to='praticas.eixoguia')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subeixos', to='praticas.versaoguia')),
            ],
            options={
                'verbose_name': 'Subeixo do guia',
                'verbose_name_plural': 'Subeixos do guia',
                'ordering': ['versao', 'eixo__ordem', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubareaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('nome_es', models.CharField(max_length=220)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='praticas.setorguia')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='praticas.versaoguia')),
            ],
            options={
                'verbose_name': 'Subarea do guia',
                'verbose_name_plural': 'Subareas do guia',
                'ordering': ['versao', 'setor__ordem', 'ordem', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='setorguia',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='praticas.versaoguia'),
        ),
        migrations.CreateModel(
            name='ReferenciaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('citacao_es', models.TextField()),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='praticas.versaoguia')),
            ],
            options={
                'verbose_name': 'Referencia do guia',
                'verbose_name_plural': 'Referencias do guia',
                'ordering': ['versao', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=160)),
                ('texto_es', models.TextField()),
                ('tipo_auditoria', models.CharField(choices=[('cumplimiento', 'Conformidade'), ('gestion', 'Gestao')], max_length=20)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('eixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas_diretas', to='praticas.eixoguia')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='praticas.subareaguia')),
                ('subeixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='praticas.subeixoguia')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='praticas.versaoguia')),
            ],
            options={
                'verbose_name': 'Pergunta do guia',
                'verbose_name_plural': 'Perguntas do guia',
                'ordering': ['versao', 'tipo_auditoria', 'ordem', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='eixoguia',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eixos', to='praticas.versaoguia'),
        ),
        migrations.CreateModel(
            name='SubareaReferenciaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_subareas', to='praticas.referenciaguia')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_referencias', to='praticas.subareaguia')),
            ],
            options={
                'verbose_name': 'Ocorrencia de referencia do guia',
                'verbose_name_plural': 'Ocorrencias de referencias do guia',
                'ordering': ['subarea', 'ordem', 'pk'],
                'indexes': [models.Index(fields=['referencia', 'subarea'], name='guia_ref_subarea_lookup')],
                'constraints': [models.UniqueConstraint(fields=('subarea', 'ordem'), name='guia_ref_ordem_subarea_unica')],
            },
        ),
        migrations.AddIndex(
            model_name='versaoguia',
            index=models.Index(fields=['situacao', 'vigente'], name='guia_versao_status_vig'),
        ),
        migrations.AddIndex(
            model_name='versaoguia',
            index=models.Index(fields=['sha256_fonte'], name='guia_versao_sha256'),
        ),
        migrations.AddConstraint(
            model_name='versaoguia',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('vigente',), name='guia_versao_vigente_unica'),
        ),
        migrations.AddConstraint(
            model_name='versaoguia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publicado_em__isnull', True), ('situacao', 'rascunho'), ('vigente', False)), models.Q(('lote_origem__isnull', False), ('publicado_em__isnull', False), ('situacao', 'publicada')), _connector='OR'), name='guia_versao_estado_coerente'),
        ),
        migrations.AddConstraint(
            model_name='versaoguia',
            constraint=models.CheckConstraint(condition=models.Q(('sha256_fonte__regex', '^[0-9a-fA-F]{64}$')), name='guia_versao_sha256_valido'),
        ),
        migrations.AddConstraint(
            model_name='subeixoguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_subeixo_codigo_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='subeixoguia',
            constraint=models.UniqueConstraint(fields=('eixo', 'ordem'), name='guia_subeixo_ordem_eixo_unica'),
        ),
        migrations.AddConstraint(
            model_name='subareaguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_subarea_codigo_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='subareaguia',
            constraint=models.UniqueConstraint(fields=('setor', 'ordem'), name='guia_subarea_ordem_setor_unica'),
        ),
        migrations.AddConstraint(
            model_name='setorguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_setor_codigo_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='setorguia',
            constraint=models.UniqueConstraint(fields=('versao', 'ordem'), name='guia_setor_ordem_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='referenciaguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_referencia_codigo_versao_unico'),
        ),
        migrations.AddIndex(
            model_name='perguntaguia',
            index=models.Index(fields=['versao', 'tipo_auditoria'], name='guia_pergunta_versao_tipo'),
        ),
        migrations.AddConstraint(
            model_name='perguntaguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_pergunta_codigo_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='perguntaguia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('eixo__isnull', False), ('subarea__isnull', True), ('subeixo__isnull', True)), models.Q(('eixo__isnull', True), ('subarea__isnull', True), ('subeixo__isnull', False)), models.Q(('eixo__isnull', True), ('subarea__isnull', False), ('subeixo__isnull', True)), _connector='OR'), name='guia_pergunta_um_escopo'),
        ),
        migrations.AddConstraint(
            model_name='perguntaguia',
            constraint=models.UniqueConstraint(condition=models.Q(('eixo__isnull', False)), fields=('eixo', 'tipo_auditoria', 'ordem'), name='guia_pergunta_ordem_eixo_unica'),
        ),
        migrations.AddConstraint(
            model_name='perguntaguia',
            constraint=models.UniqueConstraint(condition=models.Q(('subeixo__isnull', False)), fields=('subeixo', 'tipo_auditoria', 'ordem'), name='guia_pergunta_ordem_subeixo_unica'),
        ),
        migrations.AddConstraint(
            model_name='perguntaguia',
            constraint=models.UniqueConstraint(condition=models.Q(('subarea__isnull', False)), fields=('subarea', 'tipo_auditoria', 'ordem'), name='guia_pergunta_ordem_subarea_unica'),
        ),
        migrations.AddConstraint(
            model_name='eixoguia',
            constraint=models.UniqueConstraint(fields=('versao', 'codigo'), name='guia_eixo_codigo_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='eixoguia',
            constraint=models.UniqueConstraint(fields=('versao', 'ordem'), name='guia_eixo_ordem_versao_unica'),
        ),
    ]
