# Generated by Django 6.0.7 on 2026-08-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0014_experiencia_efs_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normainternacional',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='normainternacional',
            name='nome_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='normainternacional',
            name='nome_es',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='ano_texto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='cobertura_paises_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='ficha_tecnica',
            field=models.FileField(blank=True, upload_to='marcos_normativos/fichas/'),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='natureza_juridica',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='normainternacional',
            name='setores_aplicaveis',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NormaInternacionalPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises_status', to='praticas.normainternacional')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normas_internacionais_status', to='praticas.pais')),
            ],
            options={
                'verbose_name': 'País/status de marco normativo',
                'verbose_name_plural': 'Países/status de marcos normativos',
                'ordering': ['pais__nome'],
                'constraints': [models.UniqueConstraint(fields=('norma', 'pais'), name='norma_internacional_pais_unico')],
            },
        ),
    ]
