# Generated by Django 6.0.7 on 2026-08-14 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0015_lote2_marcos_normativos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoEmailPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino_apos_login', models.CharField(blank=True, default='', max_length=2048)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao_email_pendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmacao de e-mail pendente',
                'verbose_name_plural': 'Confirmacoes de e-mail pendentes',
            },
        ),
    ]
