# Generated by Django 6.0.7 on 2026-08-20 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SETORES_OFICIAIS = (
    ("agua_energia", "Água e energia", "Agua y energía", "Water and energy"),
    ("infraestrutura", "Infraestrutura", "Infraestructura", "Infrastructure"),
    (
        "biodiversidade_ecossistemas",
        "Biodiversidade e ecossistemas",
        "Biodiversidad y ecosistemas",
        "Biodiversity and ecosystems",
    ),
    ("saude", "Saúde", "Salud", "Health"),
    (
        "alimentacao_agricultura",
        "Alimentação e agricultura",
        "Alimentación y agricultura",
        "Food and agriculture",
    ),
    (
        "industria_extrativa",
        "Indústria extrativa",
        "Industria extractiva",
        "Extractive industry",
    ),
    (
        "gestao_risco_desastres",
        "Gestão de risco e desastres",
        "Gestión de riesgo y desastres",
        "Risk and disaster management",
    ),
    (
        "genero_direitos_humanos",
        "Gênero e direitos humanos",
        "Género y derechos humanos",
        "Gender and human rights",
    ),
    ("outro", "Outro", "Otro", "Other"),
    (
        "pobreza_desigualdade",
        "Pobreza e desigualdade",
        "Pobreza y desigualdad",
        "Poverty and inequality",
    ),
    ("transversal", "Transversal", "Transversal", "Cross-cutting"),
)

TIPOS_OFICIAIS = (
    ("auditoria", "Auditoria", "Auditoría", "Audit"),
    (
        "auditoria_coordenada",
        "Auditoria coordenada",
        "Auditoría coordinada",
        "Coordinated audit",
    ),
    (
        "avaliacao_politica_publica",
        "Avaliação de política pública",
        "Evaluación de política pública",
        "Public policy evaluation",
    ),
)


def _sincronizar_catalogo(modelo, itens):
    if not modelo.objects.exists():
        # Bancos novos continuam sendo populados pelos mecanismos próprios do
        # projeto. A migration de dados atua apenas sobre catálogos existentes,
        # evitando transformar dados de referência em fixtures implícitas.
        return
    for codigo, nome_pt, nome_es, nome_en in itens:
        objeto = modelo.objects.filter(codigo=codigo).first()
        if objeto is None:
            objeto = modelo.objects.filter(nome__iexact=nome_pt).first()
        if objeto is None:
            objeto = modelo.objects.create(nome=nome_pt)
        objeto.codigo = codigo
        objeto.nome = nome_pt
        objeto.nome_es = nome_es
        objeto.nome_en = nome_en
        objeto.save(update_fields=["codigo", "nome", "nome_es", "nome_en"])


def sincronizar_taxonomias(apps, schema_editor):
    _sincronizar_catalogo(apps.get_model("praticas", "Setor"), SETORES_OFICIAIS)
    _sincronizar_catalogo(
        apps.get_model("praticas", "TipoExperiencia"), TIPOS_OFICIAIS
    )


def desfazer_codigos_taxonomias(apps, schema_editor):
    apps.get_model("praticas", "Setor").objects.filter(
        codigo__in=[item[0] for item in SETORES_OFICIAIS]
    ).update(codigo=None)
    apps.get_model("praticas", "TipoExperiencia").objects.filter(
        codigo__in=[item[0] for item in TIPOS_OFICIAIS]
    ).update(codigo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0016_confirmacao_email_pendente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='outras_efs_envolvidas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='paises_participantes',
            field=models.ManyToManyField(blank=True, help_text='Selecione somente os países participantes adicionais; o país líder permanece no campo País.', related_name='experiencias_como_pais_participante', to='praticas.pais', verbose_name='Países adicionais participantes'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='tipo_auditoria',
            field=models.CharField(blank=True, choices=[('desempenho', 'Desempenho'), ('cumprimento', 'Cumprimento'), ('financeira', 'Financeira')], max_length=20),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='pais_ou_instancia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setor',
            name='codigo',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipoexperiencia',
            name='codigo',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='periodo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='situacao',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('em_revisao', 'Em revisão'), ('aprovada', 'Aprovada'), ('publicada', 'Publicada'), ('rejeitada', 'Rejeitada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20),
        ),
        migrations.RunPython(
            sincronizar_taxonomias,
            desfazer_codigos_taxonomias,
        ),
        migrations.CreateModel(
            name='PerguntaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField()),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_auditoria', to='praticas.experiencia')),
            ],
            options={
                'verbose_name': 'Pergunta de auditoria',
                'verbose_name_plural': 'Perguntas de auditoria',
                'ordering': ['ordem', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('experiencia', 'ordem'), name='pergunta_auditoria_ordem_unica'), models.CheckConstraint(condition=models.Q(('ordem__gte', 1)), name='pergunta_auditoria_ordem_positiva')],
            },
        ),
    ]
