# Generated by Django 6.0.7 on 2026-08-20 20:40

import django.db.models.deletion
from django.db import migrations, models


SETORES_OFICIAIS = (
    ("agua_energia", "Água e energia", "Agua y energía", "Water and energy"),
    ("infraestrutura", "Infraestrutura", "Infraestructura", "Infrastructure"),
    ("biodiversidade_ecossistemas", "Biodiversidade e ecossistemas", "Biodiversidad y ecosistemas", "Biodiversity and ecosystems"),
    ("saude", "Saúde", "Salud", "Health"),
    ("alimentacao_agricultura", "Alimentação e agricultura", "Alimentación y agricultura", "Food and agriculture"),
    ("industria_extrativa", "Indústria extrativa", "Industria extractiva", "Extractive industry"),
    ("gestao_risco_desastres", "Gestão de risco e desastres", "Gestión de riesgo y desastres", "Risk and disaster management"),
    ("genero_direitos_humanos", "Gênero e direitos humanos", "Género y derechos humanos", "Gender and human rights"),
    ("outro", "Outro", "Otro", "Other"),
    ("pobreza_desigualdade", "Pobreza e desigualdade", "Pobreza y desigualdad", "Poverty and inequality"),
    ("transversal", "Transversal", "Transversal", "Cross-cutting"),
)

ALIASES_INEQUIVOCOS = {
    "agua_energia": {"água e energia", "agua y energía", "water and energy", "energia", "energía", "energy", "água", "agua", "water"},
    "infraestrutura": {"infraestrutura", "infraestructura", "infrastructure"},
    "biodiversidade_ecossistemas": {"biodiversidade e ecossistemas", "biodiversidad y ecosistemas", "biodiversity and ecosystems", "bosques, biodiversidad y ecosistemas"},
    "saude": {"saúde", "salud", "health"},
    "alimentacao_agricultura": {"alimentação e agricultura", "alimentación y agricultura", "food and agriculture"},
    "industria_extrativa": {"indústria extrativa", "industria extractiva", "extractive industry", "industria extractiva y minería"},
    "gestao_risco_desastres": {"gestão de risco e desastres", "gestión de riesgo y desastres", "risk and disaster management"},
    "genero_direitos_humanos": {"gênero e direitos humanos", "género y derechos humanos", "gender and human rights"},
    "outro": {"outro", "otro", "other"},
    "pobreza_desigualdade": {"pobreza e desigualdade", "pobreza y desigualdad", "poverty and inequality"},
    "transversal": {"transversal", "cross-cutting"},
}


def corrigir_idioma_ferramentas(apps, schema_editor):
    Ferramenta = apps.get_model("praticas", "Ferramenta")
    for ferramenta in Ferramenta.objects.all().iterator():
        campos = []
        if (
            ferramenta.autor_id
            and ferramenta.titulo
            and ferramenta.titulo == ferramenta.titulo_es
            and not ferramenta.titulo_en
            and ferramenta.descricao == ferramenta.descricao_es
            and not ferramenta.descricao_en
        ):
            ferramenta.idioma_submissao = "pt"
            ferramenta.titulo_es = ""
            ferramenta.descricao_es = ""
            campos = ["idioma_submissao", "titulo_es", "descricao_es"]
        elif (
            ferramenta.autor_id
            and ferramenta.titulo_en
            and ferramenta.titulo_en == ferramenta.titulo_es
            and not ferramenta.titulo
            and ferramenta.descricao_en == ferramenta.descricao_es
            and not ferramenta.descricao
        ):
            ferramenta.idioma_submissao = "en"
            ferramenta.titulo_es = ""
            ferramenta.descricao_es = ""
            campos = ["idioma_submissao", "titulo_es", "descricao_es"]
        if campos:
            ferramenta.save(update_fields=campos)


def normalizar_setores(apps, schema_editor):
    Setor = apps.get_model("praticas", "Setor")
    if not Setor.objects.exists():
        return
    modelos_relacionados = (
        apps.get_model("praticas", "Experiencia"),
        apps.get_model("praticas", "BancoTecnico"),
        apps.get_model("praticas", "Ferramenta"),
    )
    for codigo, nome_pt, nome_es, nome_en in SETORES_OFICIAIS:
        canonico = Setor.objects.filter(codigo=codigo).first()
        aliases = []
        permitidos = ALIASES_INEQUIVOCOS[codigo]
        for setor in Setor.objects.all().order_by("pk"):
            valores = {setor.nome.casefold(), setor.nome_es.casefold(), setor.nome_en.casefold()}
            if valores & permitidos:
                aliases.append(setor)
        if canonico is None:
            canonico = aliases[0] if aliases else Setor.objects.create(nome=nome_pt)
        canonico.codigo = codigo
        canonico.nome = nome_pt
        canonico.nome_es = nome_es
        canonico.nome_en = nome_en
        canonico.save(update_fields=["codigo", "nome", "nome_es", "nome_en"])
        for alias in aliases:
            if alias.pk == canonico.pk:
                continue
            for modelo in modelos_relacionados:
                modelo.objects.filter(setor_id=alias.pk).update(setor_id=canonico.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0017_pacote_design_negocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='idioma_submissao',
            field=models.CharField(choices=[('pt', 'Português'), ('es', 'Español'), ('en', 'English')], default='es', max_length=5),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='descricao_es',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='praticas.setor'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='titulo_es',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.RunPython(
            corrigir_idioma_ferramentas,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            normalizar_setores,
            migrations.RunPython.noop,
        ),
    ]
