# Generated by Django 6.0.7 on 2026-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0018_corrigir_rascunho_ferramenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='status_publicacao',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('em_revisao', 'Em revisao'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado'), ('rejeitado', 'Rejeitado')], default='publicado', max_length=30),
        ),
    ]
