# Generated by Django 6.0.4 on 2026-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nome'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='status_iniciativa',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('execucao', 'Execução'), ('concluida', 'Concluída')], default='planejamento', max_length=20),
        ),
    ]
