# Generated by Django 6.0.4 on 2026-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0002_alter_pais_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancotecnico',
            options={'ordering': ['titulo'], 'verbose_name': 'Banco tecnico', 'verbose_name_plural': 'Banco tecnico'},
        ),
        migrations.AlterModelOptions(
            name='dimensaojusticaclimatica',
            options={'ordering': ['nome'], 'verbose_name': 'Dimensao de justica climatica', 'verbose_name_plural': 'Dimensoes de justica climatica'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-ano_execucao', 'titulo'], 'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='grupovulneravel',
            options={'ordering': ['nome'], 'verbose_name': 'Grupo vulneravel', 'verbose_name_plural': 'Grupos vulneraveis'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nome'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='tipoexperiencia',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de experiencia', 'verbose_name_plural': 'Tipos de experiencia'},
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='status_iniciativa',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('execucao', 'Execucao'), ('concluida', 'Concluida')], default='planejamento', max_length=20),
        ),
    ]
