# Generated by Django 6.0.4 on 2026-04-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praticas', '0005_funcional_negocio_mvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-ano_execucao', '-criado_em', 'titulo'], 'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
    ]
